version: '3.1'

services:
  redis:
    image: redis:latest
    container_name: redis_digitalmarket_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Volum tanimlamasi (verileri kalici hale getirmek icin)

volumes:
  redis_data: